-- ============================================================================
-- V1: Initial schema for AppTemplate (Spring Boot N-Layer Architecture - Full)
-- ============================================================================

-- Create departments table
CREATE TABLE departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50) NOT NULL UNIQUE,
    name            VARCHAR(200) NOT NULL,
    description     VARCHAR(500),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100)
);

-- Create users table
CREATE TABLE users (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                        VARCHAR(100) NOT NULL UNIQUE,
    email                           VARCHAR(255) NOT NULL UNIQUE,
    password_hash                   VARCHAR(255) NOT NULL,
    first_name                      VARCHAR(100),
    last_name                       VARCHAR(100),
    role                            VARCHAR(50) NOT NULL DEFAULT 'user',
    department_id                   BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    is_active                       BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at                   TIMESTAMPTZ,
    last_login_ip                   VARCHAR(45),
    password_reset_token            VARCHAR(255),
    password_reset_token_expires_at TIMESTAMPTZ,
    password_history                TEXT,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ,
    created_by                      VARCHAR(100),
    updated_by                      VARCHAR(100)
);

-- Create notifications table
CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           VARCHAR(200) NOT NULL,
    message         TEXT NOT NULL,
    type            VARCHAR(50) NOT NULL DEFAULT 'info',
    reference_id    VARCHAR(50),
    reference_type  VARCHAR(50),
    is_read         BOOLEAN NOT NULL DEFAULT FALSE,
    read_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create refresh_tokens table
CREATE TABLE refresh_tokens (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token             VARCHAR(255) NOT NULL UNIQUE,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at        TIMESTAMPTZ NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at        TIMESTAMPTZ,
    replaced_by_token VARCHAR(255),
    created_by_ip     VARCHAR(45),
    revoked_by_ip     VARCHAR(45),
    is_revoked        BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create uploaded_files table
CREATE TABLE uploaded_files (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name           VARCHAR(255) NOT NULL UNIQUE,
    original_file_name  VARCHAR(255) NOT NULL,
    content_type        VARCHAR(100) NOT NULL,
    file_size           BIGINT NOT NULL,
    storage_path        VARCHAR(500) NOT NULL,
    description         VARCHAR(500),
    category            VARCHAR(100),
    is_public           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100)
);

-- Create audit_logs table
CREATE TABLE audit_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name       VARCHAR(100) NOT NULL,
    entity_id         VARCHAR(50) NOT NULL,
    action            VARCHAR(50) NOT NULL,
    old_values        TEXT,
    new_values        TEXT,
    affected_columns  TEXT,
    user_id           VARCHAR(100),
    user_name         VARCHAR(200),
    details           TEXT,
    ip_address        VARCHAR(45),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Indexes
-- ============================================================================

CREATE INDEX idx_users_department_id ON users(department_id);
CREATE INDEX idx_users_password_reset_token ON users(password_reset_token);

CREATE INDEX idx_notifications_user_id_is_read ON notifications(user_id, is_read);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);

CREATE INDEX idx_uploaded_files_category ON uploaded_files(category);
CREATE INDEX idx_uploaded_files_created_by ON uploaded_files(created_by);

CREATE INDEX idx_audit_logs_entity_name ON audit_logs(entity_name);
CREATE INDEX idx_audit_logs_entity_id ON audit_logs(entity_id);
CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);
