import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1700000000000 implements MigrationInterface {
  name = 'InitialSchema1700000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "notifications" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" VARCHAR(100) NOT NULL,
        "title" VARCHAR(200) NOT NULL,
        "message" TEXT NOT NULL,
        "type" VARCHAR(50) NOT NULL DEFAULT 'info',
        "reference_id" VARCHAR(50),
        "reference_type" VARCHAR(50),
        "is_read" BOOLEAN NOT NULL DEFAULT false,
        "read_at" TIMESTAMPTZ,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_notifications_user_id_is_read" ON "notifications" ("user_id", "is_read")`);

    await queryRunner.query(`
      CREATE TABLE "uploaded_files" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "file_name" VARCHAR(255) NOT NULL UNIQUE,
        "original_file_name" VARCHAR(255) NOT NULL,
        "content_type" VARCHAR(100) NOT NULL,
        "file_size" BIGINT NOT NULL,
        "storage_path" VARCHAR(500) NOT NULL,
        "description" VARCHAR(500),
        "category" VARCHAR(100),
        "is_public" BOOLEAN NOT NULL DEFAULT false,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ,
        "created_by" VARCHAR(100),
        "updated_by" VARCHAR(100)
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_uploaded_files_category" ON "uploaded_files" ("category")`);
    await queryRunner.query(`CREATE INDEX "IDX_uploaded_files_created_by" ON "uploaded_files" ("created_by")`);

    await queryRunner.query(`
      CREATE TABLE "audit_logs" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "entity_name" VARCHAR(100) NOT NULL,
        "entity_id" VARCHAR(50) NOT NULL,
        "action" VARCHAR(50) NOT NULL,
        "old_values" TEXT,
        "new_values" TEXT,
        "affected_columns" TEXT,
        "user_id" VARCHAR(100),
        "user_name" VARCHAR(200),
        "details" TEXT,
        "ip_address" VARCHAR(45),
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_audit_logs_entity_name" ON "audit_logs" ("entity_name")`);
    await queryRunner.query(`CREATE INDEX "IDX_audit_logs_entity_id" ON "audit_logs" ("entity_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_audit_logs_user_id" ON "audit_logs" ("user_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_audit_logs_created_at" ON "audit_logs" ("created_at")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "audit_logs"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "uploaded_files"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "notifications"`);
  }
}
