import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1700000000000 implements MigrationInterface {
  name = 'InitialSchema1700000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "departments" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "code" VARCHAR(50) NOT NULL UNIQUE,
        "name" VARCHAR(200) NOT NULL,
        "description" VARCHAR(500),
        "is_active" BOOLEAN NOT NULL DEFAULT true,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "created_by" VARCHAR(100),
        "updated_by" VARCHAR(100)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "username" VARCHAR(100) NOT NULL UNIQUE,
        "email" VARCHAR(255) NOT NULL UNIQUE,
        "password_hash" VARCHAR(255),
        "first_name" VARCHAR(100),
        "last_name" VARCHAR(100),
        "role" VARCHAR(50) NOT NULL DEFAULT 'user',
        "department_id" BIGINT REFERENCES "departments"("id") ON DELETE SET NULL,
        "is_active" BOOLEAN NOT NULL DEFAULT true,
        "last_login_at" TIMESTAMPTZ,
        "last_login_ip" VARCHAR(45),
        "password_reset_token" VARCHAR(255),
        "password_reset_token_expires_at" TIMESTAMPTZ,
        "password_history" TEXT,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "created_by" VARCHAR(100),
        "updated_by" VARCHAR(100)
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_users_email" ON "users" ("email")`);
    await queryRunner.query(`CREATE INDEX "IDX_users_username" ON "users" ("username")`);
    await queryRunner.query(`CREATE INDEX "IDX_users_department_id" ON "users" ("department_id")`);

    await queryRunner.query(`
      CREATE TABLE "notifications" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "title" VARCHAR(200) NOT NULL,
        "message" TEXT NOT NULL,
        "type" VARCHAR(50) NOT NULL DEFAULT 'info',
        "reference_id" VARCHAR(50),
        "reference_type" VARCHAR(50),
        "is_read" BOOLEAN NOT NULL DEFAULT false,
        "read_at" TIMESTAMPTZ,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_notifications_user_id" ON "notifications" ("user_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_notifications_user_id_is_read" ON "notifications" ("user_id", "is_read")`);

    await queryRunner.query(`
      CREATE TABLE "refresh_tokens" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "token" VARCHAR(255) NOT NULL UNIQUE,
        "user_id" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "expires_at" TIMESTAMPTZ NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "revoked_at" TIMESTAMPTZ,
        "replaced_by_token" VARCHAR(255),
        "created_by_ip" VARCHAR(45),
        "revoked_by_ip" VARCHAR(45),
        "is_revoked" BOOLEAN NOT NULL DEFAULT false
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_token" ON "refresh_tokens" ("token")`);
    await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_user_id" ON "refresh_tokens" ("user_id")`);

    await queryRunner.query(`
      CREATE TABLE "uploaded_files" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "file_name" VARCHAR(255) NOT NULL UNIQUE,
        "original_file_name" VARCHAR(255) NOT NULL,
        "content_type" VARCHAR(100) NOT NULL,
        "file_size" BIGINT NOT NULL,
        "storage_path" VARCHAR(500),
        "description" VARCHAR(500),
        "category" VARCHAR(100),
        "is_public" BOOLEAN NOT NULL DEFAULT false,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "created_by" VARCHAR(100),
        "updated_by" VARCHAR(100)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "audit_logs" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "entity_name" VARCHAR(100) NOT NULL,
        "entity_id" VARCHAR(50),
        "action" VARCHAR(50) NOT NULL,
        "old_values" TEXT,
        "new_values" TEXT,
        "affected_columns" TEXT,
        "user_id" VARCHAR(100),
        "user_name" VARCHAR(200),
        "details" TEXT,
        "ip_address" VARCHAR(45),
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "audit_logs"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "uploaded_files"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "refresh_tokens"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "notifications"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "users"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "departments"`);
  }
}
